name: Regenerate

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: make deps

      - name: Regenerate
        run: make generate

      - name: Push
        run: |
          if [[ $(git status --porcelain --untracked-files=no) ]]; then
            make test
            git fetch --unshallow --quiet --tags
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "automated regeneration"
            make patch
          else
            echo "Nothing to commit"
          fi
